<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span><ul class="toc-item"><li><span><a href="#Scalars" data-toc-modified-id="Scalars-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span><strong>Scalars</strong></a></span></li><li><span><a href="#Vector" data-toc-modified-id="Vector-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span><strong>Vector</strong></a></span></li><li><span><a href="#Matrix" data-toc-modified-id="Matrix-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span><strong>Matrix</strong></a></span></li><li><span><a href="#Tensor" data-toc-modified-id="Tensor-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span><strong>Tensor</strong></a></span></li></ul></li><li><span><a href="#Matrix-Operations---Addition,-Subtraction,-Multiplication,-Transpose-and-Inverse" data-toc-modified-id="Matrix-Operations---Addition,-Subtraction,-Multiplication,-Transpose-and-Inverse-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Matrix Operations - Addition, Subtraction, Multiplication, Transpose and Inverse</a></span><ul class="toc-item"><li><span><a href="#Addition" data-toc-modified-id="Addition-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span><strong>Addition</strong></a></span></li><li><span><a href="#Subtraction" data-toc-modified-id="Subtraction-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span><strong>Subtraction</strong></a></span></li><li><span><a href="#Mutliplication" data-toc-modified-id="Mutliplication-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span><strong>Mutliplication</strong></a></span></li><li><span><a href="#Transpose" data-toc-modified-id="Transpose-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span><strong>Transpose</strong></a></span></li><li><span><a href="#Diagonal-Matrix" data-toc-modified-id="Diagonal-Matrix-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span><strong>Diagonal Matrix</strong></a></span></li><li><span><a href="#Identity" data-toc-modified-id="Identity-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span><strong>Identity</strong></a></span></li><li><span><a href="#array_equal()-and-allclose()-methods" data-toc-modified-id="array_equal()-and-allclose()-methods-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span><strong><code>array_equal()</code> and <code>allclose()</code> methods</strong></a></span></li><li><span><a href="#Determinant" data-toc-modified-id="Determinant-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span><strong>Determinant</strong></a></span></li><li><span><a href="#Inverse-of-a-Matrix" data-toc-modified-id="Inverse-of-a-Matrix-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span><strong>Inverse of a Matrix</strong></a></span></li></ul></li><li><span><a href="#Vector-Operations---Dot-Product-and-Cross-Product" data-toc-modified-id="Vector-Operations---Dot-Product-and-Cross-Product-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Vector Operations - Dot Product and Cross Product</a></span><ul class="toc-item"><li><span><a href="#Dot-Product-of-Vectors" data-toc-modified-id="Dot-Product-of-Vectors-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span><strong>Dot Product of Vectors</strong></a></span></li><li><span><a href="#Cross-Product-of-Vectors" data-toc-modified-id="Cross-Product-of-Vectors-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span><strong>Cross Product of Vectors</strong></a></span></li><li><span><a href="#Norm-of-a-Vector" data-toc-modified-id="Norm-of-a-Vector-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span><strong>Norm of a Vector</strong></a></span></li><li><span><a href="#Relation-between-norm-and-dot-product" data-toc-modified-id="Relation-between-norm-and-dot-product-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span><strong>Relation between norm and dot product</strong></a></span></li></ul></li><li><span><a href="#Special-Vectors-and-Matrices" data-toc-modified-id="Special-Vectors-and-Matrices-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Special Vectors and Matrices</a></span></li><li><span><a href="#Matrix-Decomposition:-Eigenvalues-&amp;-Eigenvectors" data-toc-modified-id="Matrix-Decomposition:-Eigenvalues-&amp;-Eigenvectors-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Matrix Decomposition: Eigenvalues &amp; Eigenvectors</a></span></li></ul></div>

## Introduction

* Linear algebra is a branch of mathematics that deals with equations of straight lines. 
* A line is made up of multiple points. 
* A point in 2 dimensional (2D) space is represented using two coordinates (x,y).

* General form of equation of straight line passing through any point (x,y) will be of the form ax+by+c=0. 
* Eg. 2x+1y-5=0 is an equation, where x and y is different for different point.

* In 2D space, a hyperplane is 1D. This 1D hyperplane is a line. In 3D space, a hyperplane is 2D. 
* Similarly, in an n-dimensional space, the hyperplane is n-1 dimensional.
* In 3D space, a point is represented by three coordinates (x,y,z) or (x1,x2,x3). 

![Imgur](https://i.imgur.com/i0BDrlo.png)  
![Imgur](https://i.imgur.com/jcKWgCg.png)  
<sub>source: <a href="https://towardsdatascience.com/linear-algebra-for-deep-learning-f21d7e7d7f23" target="_blank">https://towardsdatascience.com/linear-algebra-for-deep-learning-f21d7e7d7f23</a></sub>  

### **Scalars**

* a rational number, is called a 'scalar'. Eg. 2.4,5,100.9001

In [64]:
a=5              #assigns 5 to variable a 
import numpy as np
b=np.pi       #assigns value of pi to variable b 

### **Vector**

* Vector is a 1D array.
* A 1xm array is called a row vector and has 1 row and m columns. An mx1 array is called a column vector

In [65]:
v1= [[1,2,3]]               #creates 1x3 list row vector
v2= [[5],[1.5],[2]]         #creates 3x1 list column vector
v3= np.array([[8,3,2]])  #creates 1x3 ndarray row vector
print(v1,'\n', v2,'\n', v3)

[[1, 2, 3]] 
 [[5], [1.5], [2]] 
 [[8 3 2]]


### **Matrix**

* Size of a 2D array is written as mxn. ie. m rows and n columns.
* A 2D matrix with same number of rows and columns is known as a square matrix ie matrix of size mxm.

In [66]:
x=[[1,2,3],[1,2,1]]                          #creates 2x3 matrix-like list 
y=np.array([[4,2,2],[2,100,9]])         #creates 2x3 ndarray matrix
print(x)
print(y)

[[1, 2, 3], [1, 2, 1]]
[[  4   2   2]
 [  2 100   9]]


### **Tensor**

* A 'tensor' is a 3D (mxnxp) or higher dimensional array.

In [67]:
t1=np.ndarray([5,5,2])       #creates a 5x5x2 3D ndarray matrix with random values
print(t1)

[[[8.93572428e-311 4.04086640e-270]
  [2.53649295e-212 3.55959754e+180]
  [3.11730544e+150 3.89848891e+233]
  [1.98105037e-293 4.60679615e-303]
  [1.61805203e+069 3.32653858e-111]]

 [[2.71841196e-297 7.85181215e-312]
  [1.18476328e+065 6.12036321e+067]
  [1.98114253e-293 1.00809596e-109]
  [9.97959338e-110 1.61826266e+069]
  [8.40609139e-284 6.66872851e-297]]

 [[5.78336400e+067 6.45736255e+067]
  [4.55695129e-303 3.26724339e-309]
  [3.26724339e-309 4.55052120e-312]
  [5.78296122e+067 1.33360388e+241]
  [1.09974554e-309 3.96236457e-133]]

 [[3.29854299e-312 2.61261355e+257]
  [6.80693628e-230 6.52016598e+252]
  [3.98220550e+209 3.81617327e-300]
  [1.33360542e+241 2.52301056e-309]
  [1.13477778e+118 1.01313694e-311]]

 [[1.13654010e-299 1.33360508e+241]
  [2.66425060e-309 1.29014094e-263]
  [6.09249253e+247 5.03961305e-266]
  [1.13266807e+277 2.90361643e-299]
  [3.38461287e+125 9.02228871e+218]]]


## Matrix Operations - Addition, Subtraction, Multiplication, Transpose and Inverse

### **Addition**

In [68]:
a=[[4,5,2],[1,2,6]]                   # creates 2x3 matrix-like list
b=np.array([[1,2,4],[100,2,3]])    # creates 2x3 ndarray matrix
np.array(a) + b                    # variable 'a' has to be converted to an ndarray matrix 
                                      # to perform addition

array([[  5,   7,   6],
       [101,   4,   9]])

### **Subtraction**

In [69]:
a-b 

array([[  3,   3,  -2],
       [-99,   0,   3]])

### **Mutliplication**

In [70]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,1],[1,1]])

addition = a + b
subtraction = a - b 
multiplicationDot = np.dot(a,b) 
multiplicationMat = np.matmul(a,b) 

print(addition)

[[2 3]
 [4 5]]


In [71]:
print(subtraction)

[[0 1]
 [2 3]]


In [72]:
print(multiplicationDot)

[[3 3]
 [7 7]]


In [73]:
print(multiplicationMat)

[[3 3]
 [7 7]]


### **Transpose**

* A transpose of a matrix is another matrix which results from transforming all the rows of elements of the original matrix into columns. 
* If the order or shape of the matrix is  (i,j)(i,j)  then the transpose of this matrix will have a shape of  (j,i)(j,i) . 
* ie. A matrix of size mxn after transpose becomes nxm sized matrix

In [74]:
a = np.array([[1,2],[3,4]])
print(a)
print(np.transpose(a))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### **Diagonal Matrix**

* A square matrix whose non-diagonal elements are zero is called a diagonal matrix. For example: 

In [75]:
a = np.array([1,2,3,4])
d = np.diag(a)
# or simpler: d = np.diag([1,2,3,4])

print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### **Identity**

Generating Identity matrices in numpy:  
Syntax:  
`numpy.eye(n)`  -   returns an ndarray identity matrix of size nxn  
Sample code:  
`numpy.eye(2)`          # generates a 2x2 ndarray identity matrix  

In [76]:
print(np.eye(3))
print(np.eye(3, dtype='int64')) # with user input data type

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


### **`array_equal()` and `allclose()` methods**

In [77]:
# Sample code:
matrix1=[1,2.00001,3.423]          # creates a list-matrix 
matrix2=[1,2.000011,3.423]         # creates another matrix-like list with close values
print(np.allclose(matrix1,matrix2))       # returns True 
print(np.array_equal(matrix1,matrix2))    # returns False

True
False


### **Determinant**

![Imgur](https://i.imgur.com/mTOT82X.png)

In [78]:
# Find determinent of a matrix using "numpy.linalg.det" in python and store its value in variable called b.
a = np.array([[5, 4], [1, 2]])
b=np.linalg.det(a)
b

6.0

### **Inverse of a Matrix**


* only a square matrix has an Inverse.
* In mathematics, we have the concept of 'reciprocal'. If a number is multiplied by its reciprocal the result is '1'.
* The Inverse of a matrix can be determined by using the 'inv' function of 'linalg' sub-module of numpy (`numpy.linalg.inv()`)

![Imgur](https://i.imgur.com/dGqw2cg.png)  
<sub>source: <a href="https://www.onlinemathlearning.com/zero-identity-determinant-matrix-hsn-vm10.html" target="_blank">https://www.onlinemathlearning.com/zero-identity-determinant-matrix-hsn-vm10.html</a></sub>  

In [79]:
a =np.array([[3,4],[1,2]])
print(a)
inv = np.linalg.inv((a))
print(inv)
id = np.dot(a, inv)
print(id)

[[3 4]
 [1 2]]
[[ 1.  -2. ]
 [-0.5  1.5]]
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


In [80]:
a = np.array([[1,2],[3,4]])

atranspose = np.transpose(a)
ainverse = np.linalg.inv(a) 
print(atranspose, ainverse)
print(np.allclose(np.matmul(atranspose,ainverse),np.eye(np.size(atranspose,0))))

[[1 3]
 [2 4]] [[-2.   1. ]
 [ 1.5 -0.5]]
False


## Vector Operations - Dot Product and Cross Product

### **Dot Product of Vectors**

In [81]:
#Sample code:
a=[1,2,3]         #creates row vector
b=[2,3,4]         
np.dot(a,b)       # returns 20

20

**Note:** We saw earlier that if a and b are matrices of sizes mxn and nxp then numpy.dot(a,b) returns an ndarray matrix of size mxp.

### **Cross Product of Vectors**

![Imgur](https://i.imgur.com/7flLSgE.jpg)

![Imgur](https://i.imgur.com/Z9zdOsa.jpg)

In [82]:
# Syntax: 
np.cross(a,b) # returns an ndarray vector of same size, where a and b are vector arrays of same size  
                   

array([-1,  2, -1])

Note that dot product of two vectors returns a scalar and cross product of two vectors returns another vector.


### **Norm of a Vector**

* The norm of a vector x, denoted as ||x|| is a measure of a vector's magnitude. Mathematically,

![Imgur](https://i.imgur.com/5icsrBg.jpg)

In [83]:
x = np.array([1,2,3,4,5])
np.linalg.norm(x)

7.416198487095663

### **Relation between norm and dot product**


* dot product of a vector with itself is equal to the norm squared

![Imgur](https://i.imgur.com/xbFKXWX.jpg)

## Special Vectors and Matrices

**Symmetric Matrix:** If a = $a^T$ then 'a' is a symmetric matrix  
**Orthogonal Matrix:** If $a^-1$ = $a^T$ then 'a' is called an orthogonal matrix.

## Matrix Decomposition: Eigenvalues & Eigenvectors

* Decomposition means breaking of a large entity into smaller ones.
* matrix decompositon or matrix factorization means decomposing or factorizing a large matrix into smaller ones. 
* Here we will talk about decomposition of a matrix into Eigen Vectors and Eigen Values
* Every square matrix has special values called eigenvalues.

![Imgur](https://i.imgur.com/Fen84v4.png)

![Imgur](https://i.imgur.com/5h6UCKs.png)

![Imgur](https://i.imgur.com/yZt8UaD.png)

This tells us that **3 is an eigenvalue**, with the **original vector** in the multiplication problem **being an eigenvector**.



![Imgur](https://i.imgur.com/GTg2E1k.png)

* For each eigenvalue there will be an eigenvector for which the eigenvalue equation is true. 
* In python we can find eigen values and eigen vectors using "linalg" package from scipy.

In [84]:
# Find eigen values and eigen vector of an array A = [1,2,3,4]. Store the eigen values in a variable called B.
from scipy import linalg as LA
import numpy as np

A = np.array([2,3,4,6]).reshape(2,2)
print("Matrix:\n ",A)
B, C= LA.eig(A)

print("Eigen Values: ",B,"\nEigen Vectors: ",C)


Matrix:
  [[2 3]
 [4 6]]
Eigen Values:  [0.+0.j 8.+0.j] 
Eigen Vectors:  [[-0.83205029 -0.4472136 ]
 [ 0.5547002  -0.89442719]]


**Linear Algebra for Data Scientists✔**
  https://www.kaggle.com/mjbahmani/linear-algebra-for-data-scientists