<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy---numerical-computing-with-multidimensional-data-arrays" data-toc-modified-id="Numpy---numerical-computing-with-multidimensional-data-arrays-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy - numerical computing with multidimensional data arrays</a></span></li><li><span><a href="#Different-Ways-To-Create-An-Array" data-toc-modified-id="Different-Ways-To-Create-An-Array-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Different Ways To Create An Array</a></span></li><li><span><a href="#Adding/Removing-Elements" data-toc-modified-id="Adding/Removing-Elements-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Adding/Removing Elements</a></span></li><li><span><a href="#NumPy-Array-Methods" data-toc-modified-id="NumPy-Array-Methods-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>NumPy Array Methods</a></span></li><li><span><a href="#Indexing,-Slicing,-subsetting-and-broadcasting" data-toc-modified-id="Indexing,-Slicing,-subsetting-and-broadcasting-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Indexing, Slicing, subsetting and broadcasting</a></span></li><li><span><a href="#N-dimensional-array" data-toc-modified-id="N-dimensional-array-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>N-dimensional array</a></span></li><li><span><a href="#Change-or-adjust-dimensions-(3-or-more)" data-toc-modified-id="Change-or-adjust-dimensions-(3-or-more)-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Change or adjust dimensions (3 or more)</a></span><ul class="toc-item"><li><span><a href="#Using-resize()" data-toc-modified-id="Using-resize()-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Using resize()</a></span></li><li><span><a href="#Using-reshape" data-toc-modified-id="Using-reshape-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Using reshape</a></span></li></ul></li><li><span><a href="#Using-NumPy-on-Alcohol-Consumption-Data-(real-world-data)" data-toc-modified-id="Using-NumPy-on-Alcohol-Consumption-Data-(real-world-data)-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Using NumPy on Alcohol Consumption Data (real world data)</a></span></li></ul></div>

## Numpy - numerical computing with multidimensional data arrays

*  Provides vectorized operation functionality that a Python list cannot.
* Occupies less memory compared to list. Greatly increase the speed and efficiency of processing large data sets. 
* It can be utilised to perform a number of mathematical operations on arrays such as trigonometric, statistical and algebraic functions.
* library for scientific computing which is dealing with numbers and math
* It also contains random number generators.

![Imgur](https://i.imgur.com/4aL45nA.png)
![Imgur](https://i.imgur.com/azI3E1e.png)

In [1]:
import numpy as np

** Creating array from list: a one dimentional numpy array **

In [2]:
my_list = [1, 2, 3, 4, 5]

In [3]:
my_numpy_arr = np.array(my_list)
my_numpy_arr #This line show the result of the array generated

array([1, 2, 3, 4, 5])

**user defined datatype **

In [6]:
my_numpy_arr = np.array(my_list,dtype=np.float64) 
my_numpy_arr
# There are also other types available such as: Boolean, Complex,..etc


array([1., 2., 3., 4., 5.])

**Set of attributes appled on top of 1d-array**

In [8]:
# Describing a Matrix
print(my_numpy_arr.dtype)
print(my_numpy_arr.ndim) # number of dimensions
print(my_numpy_arr.shape) # shape
print(my_numpy_arr.size) # size

float64
1
(5,)
5


**Row Vector**

In [3]:
#Create a vector as a Row
vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

**Column Vector**

In [4]:
#Create vector as a Column
vector_column = np.array([[1],[2],[3]])
vector_column

array([[1],
       [2],
       [3]])

**Creating 2 dimentional array**

In [7]:
#Create a 2-D Array or Matrix
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [9]:
second_list = [[1,2,3], [5,4,1], [3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr #This line show the result of the array generated

array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

![Imgur](https://i.imgur.com/7CbWato.jpg)

**Set of attributes appled on top of 2d-array**

In [10]:
print(new_2d_arr.dtype)
print(new_2d_arr.ndim) 
print(new_2d_arr.shape)
print(new_2d_arr.size)

int64
2
(3, 3)
9


## Different Ways To Create An Array

* creating a numpy array using arange() built-in function

In [12]:
my_arange = np.arange(10)
#OR
print(my_arange)
my_arange = np.arange(3,10)
#This generates 10 digits of values from index 0 to 10.

[0 1 2 3 4 5 6 7 8 9]


**If you want to create an array with 0s:**
* We can also generate a one-dimensional array of seven zeros.

In [ ]:
my_zeros = np.zeros(7)

* Similarly, we could generate a two-dimensional array of zeros having 3 rows and 5 columns

In [ ]:
two_d = np.zeros((3,5))

**If you want to create an array with 1s:**
* We can also generate a one-dimensional array of five ones.

In [ ]:
my_ones = np.ones(5)

**If you want to create an array without any element:**
* Creating NumPy array using empty() 
* Return a new array of given shape and type, without initializing entries random values.
* unlike zeros, does not set the array values to zero, and may therefore be marginally faster. 
* On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [19]:
empty_d = np.empty((4,4), 'd') # string d is for double
print(empty_d)

[[6.91181617e-310 4.66913922e-310 0.00000000e+000 2.47032823e-323]
 [4.66913913e-310 0.00000000e+000 0.00000000e+000             nan]
 [4.66913913e-310 0.00000000e+000 0.00000000e+000             nan]
 [6.91181261e-310 6.91181259e-310 6.91181595e-310 6.91181261e-310]]


**If you want to create a range of elements:**

In [8]:
np.arange(3)
#array will contain 0,1,2

array([0, 1, 2])

**If you want to create an array where the values are linearly spaced between an interval then use:**
* Creating NumPy array using linspace() built-in function.

In [7]:
# The linspace() function returns numbers evenly spaced over a specified intervals. Say we want 15 evenly spaced points from 1 to 3, we can easily use:
lin_arr = np.linspace(1, 3, 15)
print(lin_arr)

[1.         1.14285714 1.28571429 1.42857143 1.57142857 1.71428571
 1.85714286 2.         2.14285714 2.28571429 2.42857143 2.57142857
 2.71428571 2.85714286 3.        ]


* Creating an identity matrix in NumPy

In [8]:
my_matrx = np.eye(6) #6 is the number of columns/rows you want 
print(my_matrx)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


**Random number generation:**
* Generating an array of random numbers in NumP
* generate an array of random numbers using `rand()`, `randn()` or `randint()` functions

In [9]:
# one-dimensional array of 4 objects that are uniformly distributed from 0 to 1
my_rand = np.random.rand(4)
print(my_rand)

[0.90783429 0.04334925 0.70510058 0.47323268]


In [9]:
# First, we generate a 1-d array of random 25 integers
arr = np.random.rand(25)
print(arr)

[0.896123   0.8327489  0.18599274 0.66037868 0.23640302 0.584654
 0.48097127 0.10324602 0.71351081 0.70278232 0.66097257 0.69954699
 0.54410958 0.90439894 0.48752029 0.58862486 0.69461709 0.91658024
 0.57016635 0.98324554 0.82391677 0.01885602 0.33355831 0.5234349
 0.7504907 ]


In [16]:
# a two-dimensional array of 5rows and 4columns:
my_rand = np.random.rand(5, 4)
my_rand


array([[0.36014431, 0.00550338, 0.9118491 , 0.32779085],
       [0.9232909 , 0.82271223, 0.76053489, 0.9363674 ],
       [0.79164193, 0.33359224, 0.61081042, 0.91095153],
       [0.3099429 , 0.19904805, 0.00285802, 0.30875868],
       [0.49982167, 0.12256968, 0.76572926, 0.08214017]])

* using `randint()` function to generate an array of integers

In [3]:
import numpy as np
print(np.random.randint(20)) #generates a random integer exclusive of 20
print(np.random.randint(2, 20)) #generates a random integer including 2 but excluding 20
print(np.random.randint(2, 20, 7)) #generates 7 random integers including 2 but excluding 20

7
4
[ 2 17  2 15 12  9 13]


**To Generate standard normal distribution values:**

In [20]:
np.random.standard_normal((2,4)) # samples from standard normal distribution with mean and sd

array([[-0.10221637,  1.0972533 ,  0.02014693,  3.01582451],
       [-1.9876892 , -0.54198646, -0.56624764,  0.39828398]])

## Adding/Removing Elements

* To add elements:
* To delete elements

In [4]:
a = np.random.randint(2, 20, 7)
print(a)
print(np.append(a, [1,2])) #adds 1,2 at the end
#insert can also be used if we want to insert along a given index

[15 19  7  8 15 18  4]
[15 19  7  8 15 18  4  1  2]


In [5]:
np.delete(a, 1) #1 is going to be deleted from the array

array([15,  7,  8, 15, 18,  4])

In [7]:
a = np.array([1, 2, 3])
print(a)
b = np.array([5, 4, 3])
print(b)
c = np.array([[2, 4, 8], [1, 13, 7]])
print(c)
d = np.transpose(c)
print(d)

[1 2 3]
[5 4 3]
[[ 2  4  8]
 [ 1 13  7]]
[[ 2  1]
 [ 4 13]
 [ 8  7]]


In [10]:
np.append(c, d) # Append items in array c to array d

array([ 2,  4,  8,  1, 13,  7,  2,  1,  4, 13,  8,  7])

In [9]:
np.insert(a, 1, 5, axis=0) # Insert the number '5' at index 1 on axis 0
# print(a)

array([1, 5, 2, 3])

## NumPy Array Methods

**Mathematical Operations sucha as**  
`np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()` and `np.remainder()`    
**OR**  
`+`, `-`, `*`, `/` and `%`  

In [5]:
# Import `numpy` as `np`
import numpy as np

# Initialize `x` and `y`
x = np.ones((3,4))
y = np.random.random((5,1,4))

# Add `x` and `y`
x + y

array([[[1.46056385, 1.79771535, 1.98949934, 1.16760426],
        [1.46056385, 1.79771535, 1.98949934, 1.16760426],
        [1.46056385, 1.79771535, 1.98949934, 1.16760426]],

       [[1.63557025, 1.10401616, 1.60081621, 1.07363843],
        [1.63557025, 1.10401616, 1.60081621, 1.07363843],
        [1.63557025, 1.10401616, 1.60081621, 1.07363843]],

       [[1.85713169, 1.89871147, 1.82538507, 1.80608612],
        [1.85713169, 1.89871147, 1.82538507, 1.80608612],
        [1.85713169, 1.89871147, 1.82538507, 1.80608612]],

       [[1.92862717, 1.38616018, 1.00489882, 1.76348076],
        [1.92862717, 1.38616018, 1.00489882, 1.76348076],
        [1.92862717, 1.38616018, 1.00489882, 1.76348076]],

       [[1.84979056, 1.39708119, 1.42887973, 1.04687795],
        [1.84979056, 1.39708119, 1.42887973, 1.04687795],
        [1.84979056, 1.39708119, 1.42887973, 1.04687795]]])

In [6]:
# Add `x` and `y`
np.add(x,y)

# Subtract `x` and `y`
np.subtract(x,y)

# Multiply `x` and `y`
np.multiply(x,y)

# Divide `x` and `y`
np.divide(x,y)

# Calculate the remainder of `x` and `y`
np.remainder(x,y)

array([[[0.07887231, 0.20228465, 0.01050066, 0.16197868],
        [0.07887231, 0.20228465, 0.01050066, 0.16197868],
        [0.07887231, 0.20228465, 0.01050066, 0.16197868]],

       [[0.36442975, 0.06385453, 0.39918379, 0.04270041],
        [0.36442975, 0.06385453, 0.39918379, 0.04270041],
        [0.36442975, 0.06385453, 0.39918379, 0.04270041]],

       [[0.14286831, 0.10128853, 0.17461493, 0.19391388],
        [0.14286831, 0.10128853, 0.17461493, 0.19391388],
        [0.14286831, 0.10128853, 0.17461493, 0.19391388]],

       [[0.07137283, 0.22767963, 0.00064054, 0.23651924],
        [0.07137283, 0.22767963, 0.00064054, 0.23651924],
        [0.07137283, 0.22767963, 0.00064054, 0.23651924]],

       [[0.15020944, 0.20583763, 0.14224055, 0.01556304],
        [0.15020944, 0.20583763, 0.14224055, 0.01556304],
        [0.15020944, 0.20583763, 0.14224055, 0.01556304]]])

In [3]:
# We can sort by axis
c = np.array([[2, 4, 8], [1, 13, 7]])
print(c)
c.sort(axis=0) # array([[1, 4, 7], [2, 13, 8]])
print(c)
c = np.array([[2, 4, 8], [1, 13, 7]])
c.sort(axis=1) # array([[2, 4, 8], [1, 7, 13]])
print(c)

[[ 2  4  8]
 [ 1 13  7]]
[[ 1  4  7]
 [ 2 13  8]]
[[ 2  4  8]
 [ 1  7 13]]


* Locating the maximum and minimum values of a NumPy Array

In [9]:
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#Return the max element
print(np.max(matrix))
#Return the min element
print(np.min(matrix))
#To find the max element in each column
print(np.max(matrix,axis=0))
#To find the max element in each row
print(np.max(matrix,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
[7 8 9]
[3 6 9]


In [5]:
# Using the max(), and min(), we can get the maximum or minimum values in an array.
arr_2 = np.random.randint(0, 20, 10)
print(arr_2)
print(arr_2.max()) #This gives the highest value in the array
print(arr_2.min()) #This gives the lowest value in the array

[ 1  8  3  5  7 18  8  1 18  0]
18
0


In [6]:
np.random.standard_normal((2,4)) # samples from standard normal distribution with mean and sd

array([[-0.11371833,  0.96990531,  0.66088987,  0.19046183],
       [-0.75228774, -1.83431007, -0.71404906,  0.65744652]])

* Using the `argmax()`, `argmin()` and `argsort()` functions, we can locate the index of the maximum or minimum values in an array.

In [7]:
print(arr_2.argmax()) #This shows the index of the highest value in the array
print(arr_2.argmin()) #This shows the index of the lowest value in the array

5
9


In [9]:
print(arr_2)
print(arr_2.argsort()) #This shows the indices of a sorted array

[ 1  8  3  5  7 18  8  1 18  0]
[9 0 7 2 3 4 1 6 5 8]


*  you want to know if it’s a one-dimensional or two-dimensional array, simply use the shape attribute.

`intersect1d()`

In [10]:
arr1 = np.array([3,1,2,5,5])
arr2 = np.array([3,4,4,2,4])
np.intersect1d(arr1, arr2) #it will return the intersection of 2 arrays — meaning the items that are common in both arrays

array([2, 3])

`allclose()`
* It will return True if items in two arrays are equal within a tolerance. 
* It will provide you with a great way of checking if two arrays are similar

In [11]:
arr1 = np.array([0.15,0.20,0.25,0.17])
arr2 = np.array([0.14,0.21,0.27,0.15])

In [13]:
print(np.allclose(arr1, arr2, 0.1))
print(np.allclose(arr1, arr2, 0.2))

False
True


## Indexing, Slicing, subsetting and broadcasting

* 1 dimensional array

** Indexing/Selecting elements or groups of elements from a NumPy array**

In [22]:
# Indexing NumPy arrays is similar to that of Python. You simply pass in the index you want.
my_array = np.arange(0,11)
my_array[8] #This gives us the value of element at index 8

8

* To get a range of values in an array, we will use the slice notation `:`

In [6]:
print(my_array[:])
print(my_array[2:6]) #This returns everything from index 2 to 6(exclusive)sam
print(my_array[:6]) #This returns everything from index 0 to 6(exclusive)
print(my_array[5:]) #This returns everything from index 5 to the end of the array.

[ 0  1  2  3  4  5  6  7  8  9 10]
[2 3 4 5]
[0 1 2 3 4 5]
[ 5  6  7  8  9 10]


* negative indexing

In [7]:
print(my_array[-3])  # negative indexing
print(my_array[-6:-2])  # negative slicing

8
[5 6 7 8]


* 2 dimensional array

In [8]:
# Using the double bracket notation, we will grab the value ‘60’ from the 2-d array below:
two_d_arr = np.array([[10,20,30], [40,50,60], [70,80,90]])
two_d_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

*Similarly, we can select elements in a 2-d array using either the single or double bracket `[,]` , `[][]` notation or the single bracket with colon combination `[:,:]` notation.*



* single element

In [16]:
print(two_d_arr[1][2]) #The value 60 appears is in row index 1, and column index 2
print(two_d_arr[1,2])

60
60


* rows extraction

In [25]:
two_d_arr[0] #This grabs row 0 of the array ([10, 20, 30])

array([10, 20, 30])

In [26]:
two_d_arr[2]

array([70, 80, 90])

In [10]:
two_d_arr[:] # extracting all rows

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [13]:
two_d_arr[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
two_d_arr[2:]

array([[70, 80, 90]])

In [11]:
two_d_arr[1:3]

array([[40, 50, 60],
       [70, 80, 90]])

**subsetting**

In [17]:
two_d_arr[:,:]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [19]:
# We can also go further to grab subsections of a 2-d array using the slice notation. Let’s
# grab some elements in some corners of the array:
print(two_d_arr[:1, :2]) # This returns [[10, 20]]

[[10 20]]


In [20]:
print(two_d_arr[:2, 1:]) # This returns ([[20, 30], [50, 60]])

[[20 30]
 [50 60]]


In [21]:
print(two_d_arr[:2, :2]) #This returns ([[10, 20], [40, 50]])

[[10 20]
 [40 50]]


In [22]:
print(two_d_arr[1:2, :2])

[[40 50]]


In [23]:
print(two_d_arr[:2, 1:2])

[[20]
 [50]]


In [24]:
print(two_d_arr[1:2, 1:2])

[[50]]


**Broadcasting**
* Broadcasting is a concept to do some operations even if the dimension of two arrays is not similar.
* Broadcasting is more like an automatic array allocation. 
* Broadcasting is more like magically performing the array expansion to perform some arithmetic operations such as addition.
* we will try to match up the elements using certain rules. Few essential steps involved in broadcasting are:

* Compare the last dimension of each array
* If lengths of the dimension are equal, or one of the dimension lengths is 1, then we keep working
* If lengths of dimension aren’t equal, and none of the dimension lengths is 1, then there is an error
* Repeat checking dimensions until the shortest array is out of dimensions.

In [5]:
my_array = np.arange(0,11)
# Broadcasting is a quick way to change the values of a NumPy array.
my_array[0:3] = 50
print(my_array)
#Result is: [50, 50, 50, 3, 4, 5, 6, 7, 8, 9, 10]
# In this example, we changed the values of the elements in index 0 to 3 from their initial values to 50.

[50 50 50  3  4  5  6  7  8  9 10]


* We can also perform scalar operations on an array. NumPy makes it possible through broadcasting.

In [7]:
arr = np.random.rand(25)
print(arr)
arr + 50 #This adds 50 to every element in that array

[0.74538798 0.4848558  0.57350799 0.59707832 0.31938411 0.73368175
 0.63971322 0.48766091 0.67838344 0.61213715 0.791488   0.8277216
 0.07948524 0.41983281 0.54195906 0.19846198 0.16069573 0.68326314
 0.91688731 0.4375368  0.50343994 0.20136483 0.51289335 0.32150746
 0.73900913]


array([50.74538798, 50.4848558 , 50.57350799, 50.59707832, 50.31938411,
       50.73368175, 50.63971322, 50.48766091, 50.67838344, 50.61213715,
       50.791488  , 50.8277216 , 50.07948524, 50.41983281, 50.54195906,
       50.19846198, 50.16069573, 50.68326314, 50.91688731, 50.4375368 ,
       50.50343994, 50.20136483, 50.51289335, 50.32150746, 50.73900913])

In [1]:
import numpy as np
x = np.array([[0,1,2],
             [3,4,5]])
y = np.array([7,8,9])
z = x+y
print(z)

[[ 7  9 11]
 [10 12 14]]


In [2]:
X_array = np.array(
    [
        [3,4],
        [5,7]
    ]
)
Y_array = np.array([5,2])
X_array + Y_array

array([[ 8,  6],
       [10,  9]])

**Using logical condition values extraction**

In [21]:
# We can also perform conditional and logical selections on arrays using & (AND), | (OR), <, > and == operators to compare the values in the array with the given value. Here’s how:
new_arr = np.arange(5,15)
new_arr > 10 #This returns TRUE where the elements are greater than 10 [False, False, False, False, False, False, True, True, True, True]
# Now we can print out the actual elements that were TRUE in the above conditional using:
bool_arr = new_arr > 10
new_arr[bool_arr] #This returns elements greater than 10 [11, 12, 13, 14]
new_arr[new_arr>10] #A shorter way to do what we have just done

array([11, 12, 13, 14])

* Using a combination of conditional and Logical& (AND) operators, we can get elements that are greater than 6 but less than 10.

In [22]:
new_arr[(new_arr>6) & (new_arr<10)]
# Our expected result is: ([7, 8, 9])

array([7, 8, 9])

In [2]:
import numpy as np
c = np.arange(10, 100, 5)
print(c)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [4]:
# boolean condition for each value 
c>49

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [5]:
# display the vales which satisfy the boolean condition
c[c>49]

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [9]:
# logical and condition
Bgrade = np.logical_and(c>20, c<=60)

In [10]:
c[Bgrade]

array([25, 30, 35, 40, 45, 50, 55, 60])

In [12]:
# using where condiction replace the condition satisfied value with 'NA'
val = np.where(c>20, c, 'NA')
val

array(['NA', 'NA', 'NA', '25', '30', '35', '40', '45', '50', '55', '60',
       '65', '70', '75', '80', '85', '90', '95'], dtype='<U21')

In [4]:
val = np.where(c>20, "yes", 'no')
val

array(['no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'],
      dtype='<U3')

* Performing arithmetic operations on NumPy Arrays

In [24]:
arr = np.arange(1,11)
arr * arr #Multiplies each element by itself
arr - arr #Subtracts each element from itself
arr + arr #Adds each element to itself
arr / arr #Divides each element by itself

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* Numpy also let’s you perform universal functions such as square roots, exponentials, trigonometric, etc on array

In [27]:
np.sqrt(arr) #Returns the square root of each element
np.exp(arr) #Returns the exponentials of each element
np.sin(arr) #Returns the sin of each element
np.cos(arr) #Returns the cosine of each element
np.log(arr) #Returns the logarithm of each element
np.sum(arr) #Returns the sum total of elements in the array
np.std(arr) #Returns the standard deviation of in the array

2.8722813232690143

* We can also grab the sum of columns or rows in a 2-d array:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat.sum() #Returns the sum of all the values in mat
mat.sum(axis=0) #Returns the sum of all the columns in mat (lookat top to bottom)
mat.sum(axis=1) #Returns the sum of all the rows in mat (lookat left to right) 

array([ 15,  40,  65,  90, 115])

## N-dimensional array

In [3]:
    #Creating a three dimensional array and access elements
tdarray = np.array([[['1','2','3'],['a','b','c']],[['4','5','6'],['d','e','f']],[['7','8','9'],['g','h','i']]])
    # or
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
            [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
            [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

![Imgur](https://i.imgur.com/K5dSc49.png)

* The rows are indicated as the “axis 0”
* The columns are the “axis 1”. 
* The number of the axis goes up accordingly with the number of the dimensions
* in 3-D arrays, you’ll have an additional “axis 2

In [11]:
tdarray

array([[['1', '2', '3'],
        ['a', 'b', 'c']],

       [['4', '5', '6'],
        ['d', 'e', 'f']],

       [['7', '8', '9'],
        ['g', 'h', 'i']]], dtype='<U1')

In [21]:
print(type(tdarray))
print(tdarray.dtype)
print(tdarray.ndim, tdarray.shape,tdarray.size)

<class 'numpy.ndarray'>
<U1
3 (3, 2, 3) 18


**3 dimensional array Elements accessing**

In [4]:
tdarray[0]

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U1')

In [5]:
tdarray[1]

array([['4', '5', '6'],
       ['d', 'e', 'f']], dtype='<U1')

In [6]:
tdarray[2]

array([['7', '8', '9'],
       ['g', 'h', 'i']], dtype='<U1')

In [7]:
tdarray[0,0]

array(['1', '2', '3'], dtype='<U1')

In [ ]:
# or
tdarray[0][0]

In [9]:
tdarray[0][0][0]

'1'

In [10]:
tdarray[0,0,0]

'1'

In [12]:
# to access 'h'
tdarray[2,1,1]

'h'

**Slicing**

In [16]:
tdarray[:,:,:]

array([[['1', '2', '3'],
        ['a', 'b', 'c']],

       [['4', '5', '6'],
        ['d', 'e', 'f']],

       [['7', '8', '9'],
        ['g', 'h', 'i']]], dtype='<U1')

In [13]:
tdarray[2,1,:]

array(['g', 'h', 'i'], dtype='<U1')

In [14]:
tdarray[2,:,1]

array(['8', 'h'], dtype='<U1')

## Change or adjust dimensions (3 or more)
### Using resize()

* To shrink or expand the array

In [4]:
arr = np.random.rand(120)
# Change shape and size of array in-place.
arr.resize(3,4,10) # changing to 3 dimensions
print(arr)

[[[0.40353819 0.05528676 0.47539283 0.64737901 0.46483855 0.31439084
   0.62957218 0.1161248  0.26297632 0.84083284]
  [0.50015491 0.09062982 0.54673576 0.29298789 0.26573942 0.26738979
   0.51399319 0.71953138 0.98333652 0.86675256]
  [0.45571546 0.8984992  0.52856006 0.72164108 0.96623463 0.94261075
   0.15380992 0.004293   0.93586161 0.343828  ]
  [0.98829894 0.29260247 0.38570089 0.69609562 0.26024453 0.39123467
   0.44774891 0.52133301 0.65665645 0.25176009]]

 [[0.27957055 0.49168639 0.8946928  0.5833772  0.05765919 0.26394338
   0.97567496 0.43250062 0.39834832 0.05439809]
  [0.55599498 0.56589417 0.77349676 0.88183677 0.25026648 0.45749426
   0.32643375 0.43095187 0.10294474 0.65824471]
  [0.68968503 0.04100315 0.10187313 0.78897003 0.74255229 0.1604102
   0.42490953 0.85531747 0.33503018 0.5633139 ]
  [0.03650715 0.81730912 0.65173041 0.97130459 0.32322044 0.56829712
   0.12810948 0.19112938 0.47111464 0.61507789]]

 [[0.66712383 0.82875786 0.84064653 0.93893749 0.65942758 0.8

In [6]:
print(arr[0,0,0]) 
print(arr[0,1,0]) 
print(arr[0,0,1]) 
print(arr[1,1,0])
print(arr[0,2,0]) 

0.4035381852456362
0.5001549081225771
0.055286758842339134
0.5559949836477687
0.4557154627349538


In [21]:
arr.resize(3,4,5,2) # changing to 4 dimensions
print(arr)

[[[[0.40353819 0.05528676]
   [0.47539283 0.64737901]
   [0.46483855 0.31439084]
   [0.62957218 0.1161248 ]
   [0.26297632 0.84083284]]

  [[0.50015491 0.09062982]
   [0.54673576 0.29298789]
   [0.26573942 0.26738979]
   [0.51399319 0.71953138]
   [0.98333652 0.86675256]]

  [[0.45571546 0.8984992 ]
   [0.52856006 0.72164108]
   [0.96623463 0.94261075]
   [0.15380992 0.004293  ]
   [0.93586161 0.343828  ]]

  [[0.98829894 0.29260247]
   [0.38570089 0.69609562]
   [0.26024453 0.39123467]
   [0.44774891 0.52133301]
   [0.65665645 0.25176009]]]


 [[[0.27957055 0.49168639]
   [0.8946928  0.5833772 ]
   [0.05765919 0.26394338]
   [0.97567496 0.43250062]
   [0.39834832 0.05439809]]

  [[0.55599498 0.56589417]
   [0.77349676 0.88183677]
   [0.25026648 0.45749426]
   [0.32643375 0.43095187]
   [0.10294474 0.65824471]]

  [[0.68968503 0.04100315]
   [0.10187313 0.78897003]
   [0.74255229 0.1604102 ]
   [0.42490953 0.85531747]
   [0.33503018 0.5633139 ]]

  [[0.03650715 0.81730912]
   [0.651730

In [16]:
print(arr[0,0,0,0]) 

print(arr[0,0,1,0]) 

print(arr[0,0,1,1]) 

print(arr[1,1,0,1])

print(arr[0,0,0,2]) 

0.4035381852456362


**4D numpy array indexing:**  
https://stackoverflow.com/questions/47143361/explain-this-4d-numpy-array-indexing-intuitively  
**Indexing and slicing numpy arrays:**  
https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/  

### Using reshape

* Returns an array containing the same data with a new shape.
* numpy allow us to give one of new shape parameter as -1 
* It simply means that it is an unknown dimension and we want numpy to figure it out. And numpy will figure this by looking at the 'length of the array and remaining dimensions'

In [1]:
z = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])
z.shape

NameError: name 'np' is not defined

In [4]:
# Now trying to reshape with (-1) . Result new shape is (12,) and is compatible with original shape (3,4)
z.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
# Now trying to reshape with (-1, 1) . We have provided column as 1 but rows as unknown . 
# So we get result new shape as (12, 1).again compatible with original shape(3,4)
z.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [6]:
# New shape as (-1, 2). row unknown, column 2. we get result new shape as (6, 2)
z.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [7]:
# Now trying to keep column as unknown. New shape as (1,-1). i.e, row is 1, column unknown. we get result new shape as (1, 12)
z.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [8]:
# New shape (2, -1). Row 2, column unknown. we get result new shape as (2,6)
z.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
# New shape as (3, -1). Row 3, column unknown. we get result new shape as (3,4)
z.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
# And finally, if we try to provide both dimension as unknown i.e new shape as (-1,-1). It will throw an error
z.reshape(-1, -1)

ValueError: can only specify one unknown dimension

**Flattening shape using `ravel()` function**

In [24]:
a = np.array([[1,2,3],[4,5,6]])
print('The original array is:\n', a )
b = np.ravel(a)
print(b)

The original array is:
 [[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


**Transpose of an Array**

`numpy.transpose(arr, axes)`  

arr: The array to be transposed  
axes: List of ints, corresponding to the dimensions. By default, the dimensions are reversed  

In [27]:
a = np.arange(9).reshape(3,3) 
print('The original array is:' )
print(a)
print(a.transpose())
# OR 
print(np.transpose(a))

The original array is:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


**Exercise**  
Create a 4-dimensional array, named fdarray, with elements 1,2,3,4...so on and with a shape 4,3,2,2.  
Print out the shape of the array to verify your answer. Also access the element '10' using appropriate indices, assign it to a variable target2 and print out target2.   

?

**`set_printoptions`**

In [1]:
import numpy as np
x=np.random.random(10)
print(x)

[0.1289904  0.36481258 0.0789798  0.66154939 0.31940748 0.30637188
 0.92140832 0.44340165 0.76025599 0.24222963]


***precision***

In [2]:
np.set_printoptions(precision=3)
print(x)

[0.129 0.365 0.079 0.662 0.319 0.306 0.921 0.443 0.76  0.242]


***suppress***

In [3]:
y=np.array([1.5e-10,1.5,1500])
print(y)
# [  1.500e-10   1.500e+00   1.500e+03]
np.set_printoptions(suppress=True)
print(y)

[1.5e-10 1.5e+00 1.5e+03]
[   0.     1.5 1500. ]


***threshold***

In [ ]:
np.set_printoptions(threshold=12) # threshold should be greater than the values which display (trying with sample 12)
print(np.arange(100))

In [8]:
np.set_printoptions(threshold=99) # threshold should be greater than the values which display (trying with sample 9)
print(np.arange(100))

[ 0  1  2 ... 97 98 99]


In [10]:
np.set_printoptions(threshold=100) # threshold should be greater than the values which display
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [11]:
np.set_printoptions(threshold=np.inf)
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


## Using NumPy on Alcohol Consumption Data (real world data)

* Load real world data of csv files into NumPy 
* Measuring quantities and Calculate basic statistics with NumPy
* Select items in NumPy arrays and slicing subsets of the dataset

In [ ]:
# dataset location: https://github.com/fivethirtyeight/data/blob/master/alcohol-consumption/drinks.csv
# code pulled from: https://www.packtpub.com/mapt/video/big_data_and_business_intelligence

In [1]:
# import numpy
import numpy as np

In [1]:
!head data/drinks.csv

country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
Afghanistan,0,0,0,0.0
Albania,89,132,54,4.9
Algeria,25,0,14,0.7
Andorra,245,138,312,12.4
Angola,217,57,45,5.9
Antigua & Barbuda,102,128,45,4.9
Argentina,193,25,221,8.3
Armenia,21,179,11,3.8
Australia,261,72,212,10.4


**Data loading using numpy `genfromtxt` or `loadtxt` methods:**

In [9]:
# load data
import numpy as np
dtype = dict(names=('country','beer','spirit','wine','total'),
            formats=('S64','f','f','f','f'))
booze = np.genfromtxt("data/drinks.csv", delimiter=",", dtype=dtype, skip_header=1)
booze

array([(b'Afghanistan',   0.,   0.,   0.,  0. ),
       (b'Albania',  89., 132.,  54.,  4.9),
       (b'Algeria',  25.,   0.,  14.,  0.7),
       (b'Andorra', 245., 138., 312., 12.4),
       (b'Angola', 217.,  57.,  45.,  5.9),
       (b'Antigua & Barbuda', 102., 128.,  45.,  4.9),
       (b'Argentina', 193.,  25., 221.,  8.3),
       (b'Armenia',  21., 179.,  11.,  3.8),
       (b'Australia', 261.,  72., 212., 10.4),
       (b'Austria', 279.,  75., 191.,  9.7),
       (b'Azerbaijan',  21.,  46.,   5.,  1.3),
       (b'Bahamas', 122., 176.,  51.,  6.3),
       (b'Bahrain',  42.,  63.,   7.,  2. ),
       (b'Bangladesh',   0.,   0.,   0.,  0. ),
       (b'Barbados', 143., 173.,  36.,  6.3),
       (b'Belarus', 142., 373.,  42., 14.4),
       (b'Belgium', 295.,  84., 212., 10.5),
       (b'Belize', 263., 114.,   8.,  6.8),
       (b'Benin',  34.,   4.,  13.,  1.1),
       (b'Bhutan',  23.,   0.,   0.,  0.4),
       (b'Bolivia', 167.,  41.,   8.,  3.8),
       (b'Bosnia-Herzegovina',  76.

In [5]:
# load data
dtype = dict(names=('country','beer','spirit','wine','total'),
            formats=('S64','f','f','f','f'))
booze = np.loadtxt("data/drinks.csv", delimiter=',', dtype=dtype, skiprows=1)

In [6]:
# Select data by country
booze[np.where(booze['country'] == 'Canada')]

array([],
      dtype=[('country', 'S64'), ('beer', '<f4'), ('spirit', '<f4'), ('wine', '<f4'), ('total', '<f4')])

In [7]:
# Select data teetotal countries
booze[np.where(booze['total'] == 0)]

array([(b'Afghanistan', 0., 0., 0., 0.), (b'Bangladesh', 0., 0., 0., 0.),
       (b'North Korea', 0., 0., 0., 0.), (b'Iran', 0., 0., 0., 0.),
       (b'Kuwait', 0., 0., 0., 0.), (b'Libya', 0., 0., 0., 0.),
       (b'Maldives', 0., 0., 0., 0.),
       (b'Marshall Islands', 0., 0., 0., 0.),
       (b'Mauritania', 0., 0., 0., 0.), (b'Monaco', 0., 0., 0., 0.),
       (b'Pakistan', 0., 0., 0., 0.), (b'San Marino', 0., 0., 0., 0.),
       (b'Somalia', 0., 0., 0., 0.)],
      dtype=[('country', 'S64'), ('beer', '<f4'), ('spirit', '<f4'), ('wine', '<f4'), ('total', '<f4')])

In [8]:
# Who drinks the most?
booze[np.where(booze['wine'] == np.max(booze['wine']))]

array([(b'France', 127., 151., 370., 11.8)],
      dtype=[('country', 'S64'), ('beer', '<f4'), ('spirit', '<f4'), ('wine', '<f4'), ('total', '<f4')])

In [9]:
# What is the average amount consumed?
np.mean(booze['total'])

4.7170987

In [10]:
# How much variation in the amount consumed?
np.std(booze['total'])

3.76351

<span style="color:red; font-family:brandon">Further  Resources</span>  
<a href="https://analyticsindiamag.com/beginners-guide-numpy-must-python-library-data-scientist-toolkit/" target="_blank">https://analyticsindiamag.com/beginners-guide-numpy-must-python-library-data-scientist-toolkit/</a>  
<a href="https://www.datacamp.com/community/tutorials/python-numpy-tutorial" target="_blank">https://www.datacamp.com/community/tutorials/python-numpy-tutorial</a>  
https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf  

<span style="color:red; font-family:Comic Sans MS">References</span>  
<a href="https://towardsdatascience.com/lets-talk-about-numpy-for-datascience-beginners-b8088722309f" target="_blank">https://towardsdatascience.com/lets-talk-about-numpy-for-datascience-beginners-b8088722309f</a>  